"""
GitHub Pull Request Generator.

Assembles comprehensive, reviewable PR drafts including:
1. Descriptive PR title and isolated branch name
2. Markdown summary of upstream breaking schema changes
3. Impacted downstream consumer microservice references
4. Unified code diffs
5. Test validation output
"""

import uuid
from typing import List, Optional

from self_maintaining_api.schemas import (
    CandidatePatch,
    ImpactReport,
    PullRequestDraft,
    SchemaDiffResult,
)


class PullRequestGenerator:
    """
    Constructs GitHub Pull Request drafts for automated schema maintenance.
    """

    def generate_draft(
        self,
        diff_result: SchemaDiffResult,
        impact_report: ImpactReport,
        patches: List[CandidatePatch],
        tests_passed: bool = True,
        test_summary: str = "All downstream integration and unit tests passed.",
    ) -> PullRequestDraft:
        service = diff_result.service_name
        version = diff_result.new_version
        branch_name = f"auto-api-maintenance/adapt-{service}-v{version.replace('.', '_')}"
        title = f"fix(api-contract): adapt consumer clients to {service} v{version} breaking schema"

        # Construct markdown body
        md_lines = [
            f"# Automated API Contract Adaptation: `{service}` v{version}",
            "",
            "## 1. Overview",
            f"This automated PR was generated by the **Self-Maintaining API Engine** in response to schema changes detected in the upstream `{service}` API contract.",
            "",
            "## 2. Upstream Schema Changes",
            "| Path / Symbol | Change Type | Compatibility | Description |",
            "|---|---|---|---|",
        ]

        for c in diff_result.changes:
            md_lines.append(
                f"| `{c.path}` | `{c.change_type.value}` | `{c.compatibility.value}` | {c.description} |"
            )

        md_lines.extend([
            "",
            "## 3. Downstream Repository Impact",
            f"- **Total Impacted Files**: {impact_report.total_impacted_files}",
            f"- **Affected References**: {len(impact_report.impacted_references)}",
            "",
            "| File | Line | Symbol | Reason |",
            "|---|---|---|---|",
        ])

        for ref in impact_report.impacted_references[:10]:
            md_lines.append(
                f"| `{ref.file_path}` | `{ref.line_number}` | `{ref.matched_symbol}` | {ref.impact_reason} |"
            )

        if len(impact_report.impacted_references) > 10:
            md_lines.append(f"*(and {len(impact_report.impacted_references) - 10} more references)*")

        md_lines.extend([
            "",
            "## 4. Test Verification Status",
            f"- **Tests Passed**: {'✅ YES' if tests_passed else '❌ FAILED'}",
            f"- **Summary**: {test_summary}",
            "",
            "## 5. Candidate Patches",
        ])

        for p in patches:
            md_lines.extend([
                f"### `{p.file_path}`",
                f"*{p.explanation}*",
                "```diff",
                p.diff_unified,
                "```",
                "",
            ])

        md_lines.extend([
            "---",
            "*Generated autonomously by the Self-Maintaining API Engine. Verified against local test suite before PR submission.*",
        ])

        body = "\n".join(md_lines)
        pr_id = f"PR-{uuid.uuid4().hex[:6].upper()}"

        return PullRequestDraft(
            pr_id=pr_id,
            title=title,
            branch_name=branch_name,
            target_branch="master",
            body_markdown=body,
            patches=patches,
            tests_passed=tests_passed,
            test_summary=test_summary,
        )
