apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: incident-platform
type: Opaque
stringData:
  POSTGRES_PASSWORD: "changeme_in_production"
  ORDER_POSTGRES_PASSWORD: "changeme_in_production"
  PAYMENT_POSTGRES_PASSWORD: "changeme_in_production"
